from pathlib import Path
import json
import typer
from pydantic import ValidationError

from .config import GenerationRequest, ShotRequest
from .pipeline import VideoGenerator

app = typer.Typer(help="Goldman AI Video CLI")


def _build_request(
    *,
    prompt: str,
    output: Path,
    frames: int | None,
    duration: int | None,
    width: int,
    height: int,
    resolution: str,
    fps: int,
    watermark: str,
    audio: Path | None,
    audio_start: float,
    audio_volume: float,
    audio_loop: bool,
    image: Path | None = None,
    shots: list[ShotRequest] | None = None,
    gpu: str = "auto",
    low_vram: bool = False,
    precision: str = "fp16",
    use_diffusers: bool = False,
    vae: str | None = None,
    vae_tiling: bool = False,
    vae_slicing: bool = False,
    animation_style: str = "pan_zoom",
    animation_intensity: float = 1.0,
) -> GenerationRequest:
    req = GenerationRequest(
        prompt=prompt,
        output_path=output,
        num_frames=frames or 120,
        duration_seconds=duration,
        width=width,
        height=height,
        resolution_preset=resolution,
        fps=fps,
        watermark_text=watermark,
        audio_path=audio,
        audio_start_sec=audio_start,
        audio_volume=audio_volume,
        audio_loop=audio_loop,
        image_path=image,
        shots=shots,
        device=gpu,
        low_vram=low_vram,
        precision=precision,
        use_diffusers=use_diffusers,
        vae_model_id=vae,
        vae_tiling=vae_tiling,
        vae_slicing=vae_slicing,
        animation_style=animation_style,
        animation_intensity=animation_intensity,
    )
    return req


@app.command("text2video")
def text2video(
    prompt: str,
    output: Path = Path("outputs/text2video.mp4"),
    frames: int | None = None,
    duration: int | None = typer.Option(None, help="Duration seconds: 5/10/15/20/25"),
    width: int = 576,
    height: int = 320,
    resolution: str = typer.Option("custom", help="custom | 1080p | 4k"),
    fps: int = 24,
    watermark: str = "Generated by Goldman AI",
    audio: Path | None = None,
    audio_start: float = 0.0,
    audio_volume: float = 1.0,
    audio_loop: bool = False,
    gpu: str = typer.Option("auto", help="auto | cpu | cuda"),
    low_vram: bool = False,
    precision: str = typer.Option("fp16", help="fp32 | fp16 | bf16"),
    use_diffusers: bool = typer.Option(False, "--use-diffusers", help="Use diffusers backend instead of mock"),
    vae: str | None = typer.Option(None, "--vae", help="Optional VAE model id"),
    vae_tiling: bool = typer.Option(False, "--vae-tiling", help="Enable VAE tiling"),
    vae_slicing: bool = typer.Option(False, "--vae-slicing", help="Enable VAE slicing"),
    animation_style: str = typer.Option("pan_zoom", help="pan | zoom | pan_zoom"),
    animation_intensity: float = typer.Option(1.0, help="Deterministic animation strength"),
):
    req = _build_request(
        prompt=prompt,
        output=output,
        frames=frames,
        duration=duration,
        width=width,
        height=height,
        resolution=resolution,
        fps=fps,
        watermark=watermark,
        audio=audio,
        audio_start=audio_start,
        audio_volume=audio_volume,
        audio_loop=audio_loop,
        gpu=gpu,
        low_vram=low_vram,
        precision=precision,
        use_diffusers=use_diffusers,
        vae=vae,
        vae_tiling=vae_tiling,
        vae_slicing=vae_slicing,
        animation_style=animation_style,
        animation_intensity=animation_intensity,
    )
    out = VideoGenerator().generate(req)
    typer.echo(f"Saved: {out}")


@app.command("image2video")
def image2video(
    prompt: str,
    image: Path,
    output: Path = Path("outputs/image2video.mp4"),
    frames: int | None = None,
    duration: int | None = typer.Option(None, help="Duration seconds: 5/10/15/20/25"),
    width: int = 576,
    height: int = 320,
    resolution: str = typer.Option("custom", help="custom | 1080p | 4k"),
    fps: int = 24,
    watermark: str = "Generated by Goldman AI",
    audio: Path | None = None,
    audio_start: float = 0.0,
    audio_volume: float = 1.0,
    audio_loop: bool = False,
    gpu: str = typer.Option("auto", help="auto | cpu | cuda"),
    low_vram: bool = False,
    precision: str = typer.Option("fp16", help="fp32 | fp16 | bf16"),
    use_diffusers: bool = typer.Option(False, "--use-diffusers", help="Use diffusers backend instead of mock"),
    vae: str | None = typer.Option(None, "--vae", help="Optional VAE model id"),
    vae_tiling: bool = typer.Option(False, "--vae-tiling", help="Enable VAE tiling"),
    vae_slicing: bool = typer.Option(False, "--vae-slicing", help="Enable VAE slicing"),
    animation_style: str = typer.Option("pan_zoom", help="pan | zoom | pan_zoom"),
    animation_intensity: float = typer.Option(1.0, help="Deterministic animation strength"),
):
    req = _build_request(
        prompt=prompt,
        output=output,
        frames=frames,
        duration=duration,
        width=width,
        height=height,
        resolution=resolution,
        fps=fps,
        watermark=watermark,
        audio=audio,
        audio_start=audio_start,
        audio_volume=audio_volume,
        audio_loop=audio_loop,
        image=image,
        gpu=gpu,
        low_vram=low_vram,
        precision=precision,
        use_diffusers=use_diffusers,
        vae=vae,
        vae_tiling=vae_tiling,
        vae_slicing=vae_slicing,
        animation_style=animation_style,
        animation_intensity=animation_intensity,
    )
    out = VideoGenerator().generate(req)
    typer.echo(f"Saved: {out}")


@app.command("multishot")
def multishot(
    spec: Path,
    output: Path = Path("outputs/multishot.mp4"),
    width: int = 576,
    height: int = 320,
    fps: int = 24,
    resolution: str = typer.Option("custom", help="custom | 1080p | 4k"),
    watermark: str = "Generated by Goldman AI",
    audio: Path | None = None,
    audio_start: float = 0.0,
    audio_volume: float = 1.0,
    audio_loop: bool = False,
    gpu: str = typer.Option("auto", help="auto | cpu | cuda"),
    low_vram: bool = False,
    precision: str = typer.Option("fp16", help="fp32 | fp16 | bf16"),
    use_diffusers: bool = typer.Option(False, "--use-diffusers", help="Use diffusers backend instead of mock"),
    vae: str | None = typer.Option(None, "--vae", help="Optional VAE model id"),
    vae_tiling: bool = typer.Option(False, "--vae-tiling", help="Enable VAE tiling"),
    vae_slicing: bool = typer.Option(False, "--vae-slicing", help="Enable VAE slicing"),
):
    if not spec.exists():
        raise typer.BadParameter(f"Spec file not found: {spec}")

    data = _load_shot_spec(spec)
    shots_data = data.get("shots")
    if not shots_data:
        raise typer.BadParameter("Spec must include a non-empty 'shots' list")

    try:
        shots = [ShotRequest.model_validate(shot) for shot in shots_data]
    except ValidationError as exc:
        raise typer.BadParameter(f"Invalid shot spec: {exc}") from exc
    prompt = data.get("prompt", "multi-shot generation")

    req = _build_request(
        prompt=prompt,
        output=output,
        frames=None,
        duration=None,
        width=width,
        height=height,
        resolution=resolution,
        fps=fps,
        watermark=watermark,
        audio=audio,
        audio_start=audio_start,
        audio_volume=audio_volume,
        audio_loop=audio_loop,
        shots=shots,
        gpu=gpu,
        low_vram=low_vram,
        precision=precision,
        use_diffusers=use_diffusers,
        vae=vae,
        vae_tiling=vae_tiling,
        vae_slicing=vae_slicing,
        animation_style="pan_zoom",
        animation_intensity=1.0,
    )
    out = VideoGenerator().generate(req)
    typer.echo(f"Saved: {out}")


@app.command("models")
def models(raw_json: bool = typer.Option(False, "--json", help="Output raw JSON")) -> None:
    catalog = VideoGenerator.model_catalog()
    if raw_json:
        typer.echo(json.dumps(catalog, indent=2))
        return

    validated = catalog.get("validated", {})
    typer.echo("Configured model catalog:")
    for key, value in catalog.get("catalog", {}).items():
        typer.echo(f"- {key}: {value.get('model_id')} ({value.get('notes')})")

    typer.echo("\nValidated selections:")
    for mode in ("text2video", "image2video"):
        sel = validated.get(mode, {})
        typer.echo(f"- {mode}: model={sel.get('model_id')} vae={sel.get('vae_model_id')}")

    constraints = validated.get("constraints", {})
    if constraints:
        typer.echo(f"\nConstraints: {constraints}")


def _load_shot_spec(spec: Path) -> dict:
    suffix = spec.suffix.lower()
    if suffix == ".json":
        return json.loads(spec.read_text())

    if suffix in {".yml", ".yaml"}:
        try:
            import yaml  # type: ignore
        except ModuleNotFoundError as exc:
            raise typer.BadParameter("YAML spec requires PyYAML installed") from exc
        loaded = yaml.safe_load(spec.read_text())
        if not isinstance(loaded, dict):
            raise typer.BadParameter("YAML spec root must be a mapping/object")
        return loaded

    raise typer.BadParameter("Spec file must be .json, .yml, or .yaml")
