from pathlib import Path
from typing import Literal
from pydantic import BaseModel, Field, model_validator


DurationSeconds = Literal[5, 10, 15, 20, 25]
ResolutionPreset = Literal["custom", "1080p", "4k"]
DevicePreset = Literal["auto", "cpu", "cuda"]
PrecisionPreset = Literal["fp32", "fp16", "bf16"]


class ShotRequest(BaseModel):
    prompt: str = Field(min_length=1)
    image_path: Path | None = None
    num_frames: int = Field(default=120, gt=0)
    fps: int = Field(default=24, gt=0)
    transition: Literal["cut", "crossfade"] = "cut"
    transition_frames: int = Field(default=0, ge=0)
    camera: str | None = None
    style: str | None = None

    @model_validator(mode="after")
    def normalize_transition_fields(self) -> "ShotRequest":
        if self.transition == "cut" and self.transition_frames != 0:
            self.transition_frames = 0
        return self


class GenerationRequest(BaseModel):
    prompt: str = Field(min_length=1)
    negative_prompt: str = ""
    width: int = 576
    height: int = 320
    resolution_preset: ResolutionPreset = "custom"
    duration_seconds: DurationSeconds | None = None
    num_frames: int = Field(default=120, gt=0)
    num_inference_steps: int = 30
    guidance_scale: float = 6.0
    fps: int = Field(default=24, gt=0)
    seed: int | None = None
    image_path: Path | None = None
    shots: list[ShotRequest] | None = None
    audio_path: Path | None = None
    audio_start_sec: float = Field(default=0.0, ge=0)
    audio_volume: float = Field(default=1.0, ge=0)
    audio_loop: bool = False
    device: DevicePreset = "auto"
    low_vram: bool = False
    precision: PrecisionPreset = "fp16"
    output_path: Path = Path("outputs/generated.mp4")
    watermark_text: str = "Generated by Goldman AI"

    @model_validator(mode="after")
    def apply_presets(self) -> "GenerationRequest":
        if self.resolution_preset == "1080p":
            self.width, self.height = 1920, 1080
        elif self.resolution_preset == "4k":
            self.width, self.height = 3840, 2160

        if self.duration_seconds is not None:
            self.num_frames = self.duration_seconds * self.fps

        return self


OPEN_SOURCE_MODELS = {
    "text_to_video": {
        "model_id": "THUDM/CogVideoX-5b",
        "notes": "High quality open-source T2V; requires strong GPU VRAM.",
    },
    "image_to_video": {
        "model_id": "stabilityai/stable-video-diffusion-img2vid-xt",
        "notes": "Open model for image-conditioned video generation.",
    },
}
